### ISSUE TITLE
sameInstant matcher doesn't handle null

### ISSUE THREAD

**Issue by jacobg** [eXparity/hamcrest-date#19]
Given that hamcrest is supposed to make tests concise and easy to read, it'd be nice to have a matcher like sameInstantOrNull, or something like that. Current behavior is NullPointerException:

```
java.lang.NullPointerException
	at org.exparity.hamcrest.date.core.wrapper.DateWrapper.<init>(DateWrapper.java:30)
	at org.exparity.hamcrest.date.DateMatchers.sameInstant(DateMatchers.java:557)
```

**Comment by stewbis** [comment]
Hi, I agree, it should definately not throw a NullPointerException but return false. I'll apply a fix which will be included in the next release

**Comment by jacobg** [comment]
Thanks!

**Comment by stewbis** [comment]
Hi, Just to keep you up to date. Many of the calls can suffer NullPointerException if the expectation is null so i'm setting up tests and applying the fixes for all. It may take a little while to fix them all up. Will reply on this post once they're resolved. Thanks, Stewart
